services:
  backend-api:
    image: minh0311/rental-backend:1.0
    container_name: rental-api

    ports:
      - "8081:8080"

    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver

    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Pass123

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: