services:
  - type: web
    name: rental-management-api
    runtime: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: FileStorage__Provider
        value: Azure
      - key: AzureStorage__ConnectionString
        sync: false
      - key: AzureStorage__ContainerName
        value: rental-uploads
